---
- hosts: localhost
  tasks:
 # Basic AMI Creation
    - ec2_ami:
#        aws_access_key: xxxxxxxxxxxxxxxxxxxxxxx
#        aws_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        region: us-east-1
        instance_id: i-37d06fb0
        wait: yes
        name: newtest
#        tags:
#          Name: newtest
#          Service: TestService
      register: instance
      register: ami 
