---
- hosts: localhost
  vars:
    instance_id:  "FAIL### i-nstanceID Needed"
    aws_region: "us-east-1"
    new_ami_name: "RHEL_Core1"

  tasks:
  #Basic AMI Creation
  - name: Creating AMI from Instance
    ec2_ami:
      region:  "{{ aws_region }}"
      instance_id: "{{ instance_id }}"
      wait: yes
      name: "{{ new_ami_name }}"
      state: present
    register: instance 
  - debug: var=instance.image_id
  
  - name: Create an Instance from the New AMI
    ec2:
      region:  "{{ aws_region }}"
      instance_type: t2.micro
      image: "{{ instance.image_id }}"
      wait: yes
      count: 1